# Generated by Django 4.2 on 2024-04-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("castbox", "0002_alter_customuser_options_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="title",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Title"
            ),
        ),
    ]
