# Generated by Django 4.2 on 2024-04-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("castbox", "0005_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="channel",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="episode",
        ),
        migrations.AddField(
            model_name="profile",
            name="channel",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="profiles",
                to="castbox.channel",
                verbose_name="Channels",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="comment",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="profiles",
                to="castbox.comment",
                verbose_name="Comments",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="episode",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="profiles",
                to="castbox.episode",
                verbose_name="Episodes",
            ),
        ),
    ]
