# Generated by Django 4.2 on 2024-04-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("castbox", "0007_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="like",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="profiles",
                to="castbox.like",
                verbose_name="Likes",
            ),
        ),
    ]
