# Generated by Django 4.2 on 2024-04-26 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("castbox", "0010_mention_profile_mention"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mention",
            name="channel",
        ),
        migrations.RemoveField(
            model_name="mention",
            name="episode",
        ),
    ]
