# Generated by Django 4.2 on 2024-04-26 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("castbox", "0011_remove_mention_channel_remove_mention_episode"),
    ]

    operations = [
        migrations.AddField(
            model_name="mention",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentions",
                to="castbox.channel",
                verbose_name="Channel",
            ),
        ),
        migrations.AddField(
            model_name="mention",
            name="episode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentions",
                to="castbox.episode",
                verbose_name="Episode",
            ),
        ),
    ]
