# Generated by Django 4.2 on 2024-04-26 23:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("castbox", "0014_profile_playlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="channel",
        ),
    ]
