# Generated by Django 4.2 on 2024-05-03 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0001_initial"),
        ("castbox", "0016_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="channel.channel",
                verbose_name="Channel",
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episodes",
                to="channel.channel",
                verbose_name="Channel",
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follows",
                to="channel.channel",
                verbose_name="Channel",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="channel.channel",
                verbose_name="Channel",
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="channel.channel",
                verbose_name="Channel",
            ),
        ),
        migrations.AlterField(
            model_name="mention",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentions",
                to="channel.channel",
                verbose_name="Channel",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="channel",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="profiles",
                to="channel.channel",
                verbose_name="Channels",
            ),
        ),
        migrations.DeleteModel(
            name="Channel",
        ),
    ]
