# Generated by Django 4.2 on 2024-05-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0001_initial"),
        ("castbox", "0018_remove_comment_author_remove_comment_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="comment",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="profiles",
                to="comment.comment",
                verbose_name="Comments",
            ),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
