# Generated by Django 4.2 on 2024-05-03 18:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("castbox", "0019_alter_profile_comment_delete_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="channel",
        ),
        migrations.RemoveField(
            model_name="follow",
            name="user",
        ),
    ]
