# Generated by Django 4.2 on 2024-05-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("castbox", "0020_remove_follow_channel_remove_follow_user"),
        ("follow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="follow",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="profiles",
                to="follow.follow",
                verbose_name="Follows",
            ),
        ),
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
