# Generated by Django 4.2 on 2024-05-03 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("castbox", "0023_alter_like_episode_alter_log_episode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="channel",
        ),
        migrations.RemoveField(
            model_name="like",
            name="episode",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
    ]
