# Generated by Django 4.2 on 2024-05-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("like", "0001_initial"),
        ("castbox", "0024_remove_like_channel_remove_like_episode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="like",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="profiles",
                to="like.like",
                verbose_name="Likes",
            ),
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
