# Generated by Django 4.2 on 2024-05-03 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("castbox", "0026_delete_log"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mention",
            name="channel",
        ),
        migrations.RemoveField(
            model_name="mention",
            name="episode",
        ),
        migrations.RemoveField(
            model_name="mention",
            name="user",
        ),
    ]
