# Generated by Django 4.2 on 2024-05-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("castbox", "0027_remove_mention_channel_remove_mention_episode_and_more"),
        ("mention", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="mention",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="profiles",
                to="mention.mention",
                verbose_name="Mentions",
            ),
        ),
        migrations.DeleteModel(
            name="Mention",
        ),
    ]
