# Generated by Django 4.2 on 2024-05-03 23:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("castbox", "0028_alter_profile_mention_delete_mention"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="episode",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="user",
        ),
    ]
