# Generated by Django 4.2 on 2024-05-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlist", "0001_initial"),
        ("castbox", "0029_remove_playlist_episode_remove_playlist_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="playlist",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="profiles",
                to="playlist.playlist",
                verbose_name="Playlists",
            ),
        ),
        migrations.DeleteModel(
            name="Playlist",
        ),
    ]
