# Generated by Django 4.2 on 2024-05-04 00:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("castbox", "0030_alter_profile_playlist_delete_playlist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
